server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dhlpj/spring-cloud-config-demo-rep.git
          username: dhlpj
          password: 