server:
  port: 8050
spring:
  application:
    name: microservice-file-upload    #注册到Eureka Server上的应用名称
  http:
    multipart:
      max-file-size: 2000Mb #默认1M
      max-request-size: 2500Mb  #默认10M
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true